### ISSUE TITLE
通过api/users/创建用户进入死循环

### ISSUE THREAD

**Issue by Gooooodman** [xufqing/rest_xops#8]
{
	"username":"yangjuni",
	"name":"杨三郎",
	"email":"yangjun@mibi.net",
	"mobile":"13265118888"
}

--------------

登陆之后，前端一直循环发起请求

HTTP GET /auth/build/menus/ 200 [0.03, 192.168.232.1:57465]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/info/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57566]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57465]
HTTP GET /auth/build/menus/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57465]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57566]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/info/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/build/menus/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57465]
HTTP GET /auth/info/ 200 [0.02, 192.168.232.1:57465]
HTTP GET /auth/build/menus/ 200 [0.02, 192.168.232.1:57566]
HTTP OPTIONS /api/users/4/ 200 [0.00, 192.168.232.1:57603]
HTTP GET /auth/info/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/build/menus/ 200 [0.01, 192.168.232.1:57566]
HTTP GET /auth/build/menus/ 200 [0.14, 192.168.232.1:57465]
HTTP GET /media/image/default.png 200 [0.00, 192.168.232.1:575

## 手动添加 给其角色 恢复正常
没有给其角色的用户都会出现无限循环请求

**Comment by xufqing** [comment]
@Gooooodman 如果新建用户不分配角色确实会这样，之后有时间我会修复的

**Comment by Gooooodman** [comment]
@xufqing 嗯，非常棒的系统。可惜不会vue
